services:
  coredns:
    container_name: coredns
    image: coredns/coredns:latest
    restart: always
    networks:
      docker:
        ipv4_address: 192.168.2.53
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
    command: -conf /etc/coredns/Corefile

networks:
  docker:
    # To create the macvlan network, run the following command:
    # docker network create -d macvlan --ipv6 \
    #   -o parent=ens19 \
    #   --subnet=192.168.2.0/24 --gateway=192.168.2.1 \
    #   --ip-range=192.168.2.128/25 docker
    external: true
